/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CreateProductRouteImport } from './routes/create-product'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyProductsRouteImport } from './routes/my-products'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentMethodsRouteImport } from './routes/payment-methods'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ChatChatIdRouteImport } from './routes/chat_.$chatId'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as StoreIdRouteImport } from './routes/store/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateProductRoute = CreateProductRouteImport.update({
  id: '/create-product',
  path: '/create-product',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProductsRoute = MyProductsRouteImport.update({
  id: '/my-products',
  path: '/my-products',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsRoute = PaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat_/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIdRoute = StoreIdRouteImport.update({
  id: '/store/$id',
  path: '/store/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/create-product': typeof CreateProductRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/my-products': typeof MyProductsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/splash': typeof SplashRoute
  '/wishlist': typeof WishlistRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/product/$id': typeof ProductIdRoute
  '/store/$id': typeof StoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/create-product': typeof CreateProductRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/my-products': typeof MyProductsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/splash': typeof SplashRoute
  '/wishlist': typeof WishlistRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/product/$id': typeof ProductIdRoute
  '/store/$id': typeof StoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/chat': typeof ChatRoute
  '/checkout': typeof CheckoutRoute
  '/create-product': typeof CreateProductRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/my-products': typeof MyProductsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/splash': typeof SplashRoute
  '/wishlist': typeof WishlistRoute
  '/chat_/$chatId': typeof ChatChatIdRoute
  '/product/$id': typeof ProductIdRoute
  '/store/$id': typeof StoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/chat'
    | '/checkout'
    | '/create-product'
    | '/help'
    | '/login'
    | '/my-products'
    | '/notifications'
    | '/orders'
    | '/payment-methods'
    | '/privacy-policy'
    | '/profile'
    | '/search'
    | '/splash'
    | '/wishlist'
    | '/chat/$chatId'
    | '/product/$id'
    | '/store/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/chat'
    | '/checkout'
    | '/create-product'
    | '/help'
    | '/login'
    | '/my-products'
    | '/notifications'
    | '/orders'
    | '/payment-methods'
    | '/privacy-policy'
    | '/profile'
    | '/search'
    | '/splash'
    | '/wishlist'
    | '/chat/$chatId'
    | '/product/$id'
    | '/store/$id'
  id:
    | '__root__'
    | '/'
    | '/addresses'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/chat'
    | '/checkout'
    | '/create-product'
    | '/help'
    | '/login'
    | '/my-products'
    | '/notifications'
    | '/orders'
    | '/payment-methods'
    | '/privacy-policy'
    | '/profile'
    | '/search'
    | '/splash'
    | '/wishlist'
    | '/chat_/$chatId'
    | '/product/$id'
    | '/store/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressesRoute: typeof AddressesRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  ChatRoute: typeof ChatRoute
  CheckoutRoute: typeof CheckoutRoute
  CreateProductRoute: typeof CreateProductRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MyProductsRoute: typeof MyProductsRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  PaymentMethodsRoute: typeof PaymentMethodsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SplashRoute: typeof SplashRoute
  WishlistRoute: typeof WishlistRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
  ProductIdRoute: typeof ProductIdRoute
  StoreIdRoute: typeof StoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-product': {
      id: '/create-product'
      path: '/create-product'
      fullPath: '/create-product'
      preLoaderRoute: typeof CreateProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-products': {
      id: '/my-products'
      path: '/my-products'
      fullPath: '/my-products'
      preLoaderRoute: typeof MyProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods': {
      id: '/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat_/$chatId': {
      id: '/chat_/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$id': {
      id: '/store/$id'
      path: '/store/$id'
      fullPath: '/store/$id'
      preLoaderRoute: typeof StoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressesRoute: AddressesRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  ChatRoute: ChatRoute,
  CheckoutRoute: CheckoutRoute,
  CreateProductRoute: CreateProductRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MyProductsRoute: MyProductsRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  PaymentMethodsRoute: PaymentMethodsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SplashRoute: SplashRoute,
  WishlistRoute: WishlistRoute,
  ChatChatIdRoute: ChatChatIdRoute,
  ProductIdRoute: ProductIdRoute,
  StoreIdRoute: StoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
